parent=base
styles=css/glass-theme.css

# Classes estruturais esperadas pelo base theme
kcLoginClass=login-pf-page
kcFormCardClass=card-pf
kcFormHeaderClass=login-pf-header

# Formulários e botões compatíveis com o nosso CSS
kcFormClass=form-horizontal
kcFormGroupClass=form-group
kcLabelClass=control-label
kcInputClass=form-control
kcButtonClass=btn
kcButtonPrimaryClass=btn-primary
kcButtonDefaultClass=btn-default
kcButtonBlockClass=btn-block

# Password Visibility
kcInputGroup=input-group
kcFormPasswordVisibilityButtonClass=btn btn-password-toggle
kcFormPasswordVisibilityIconShow=fa-regular fa-eye
kcFormPasswordVisibilityIconHide=fa-regular fa-eye-slash
kcFormOptionsWrapperClass=form-options

# JS Scripts
scripts=js/theme-toggle.js
